//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idfinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("idfinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13D1136F612F4F5E3CAD1102FF2E9E31.
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///and
        ///to
        ///a
        ///in
        ///for
        ///is
        ///on
        ///that
        ///by
        ///this
        ///with
        ///i
        ///you
        ///it
        ///not
        ///or
        ///be
        ///are
        ///from
        ///at
        ///as
        ///your
        ///all
        ///have
        ///new
        ///more
        ///an
        ///was
        ///we
        ///will
        ///home
        ///can
        ///us
        ///if
        ///page
        ///my
        ///has
        ///free
        ///but
        ///our
        ///one
        ///do
        ///no
        ///time
        ///they
        ///site
        ///he
        ///up
        ///may
        ///what
        ///news
        ///out
        ///use
        ///any
        ///see
        ///only
        ///so
        ///his
        ///when
        ///here
        ///who
        ///web
        ///also
        ///now
        ///help
        ///get
        ///pm
        ///view
        ///c
        ///e
        ///am
        ///been
        ///how
        ///were
        ///me
        ///s
        ///some
        ///its
        ///like
        ///x
        ///than
        ///find
        ///date
        ///back
        ///top
        ///had
        ///list
        ///name
        ///just
        ///over
        ///year
        ///day
        ///into
        ///two
        ///n
        ///re
        ///next
        ///used
        ///go
        ///b
        ///work
        ///last
        ///most
        ///buy
        ///data
        ///make
        ///them
        ///post
        ///her
        ///city
        ///t
        ///add
        ///such
        ///best
        ///then
        ///jan
        ///good
        ///well
        ///d
        ///info
        ///high
        ///m
        ///each
        ///she
        ///ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
